#! /bin/sh
# /etc/init.d/heartbeat_daemon

#
### BEGIN INIT INFO
#Provides:          heartbeat_daemon
#Processname:       heartbeat_daemon
#Required-Start:    $network
#Required-Stop:     $network
#Default-Start:     S 2 
#Default-Stop:      0 1 6
#Short-Description: Heart Beat 
#Description:       It keeps the server knows that i'm alive.
### END INIT INFO

#exec 1>/tmp/heartbeat_daemon.log 2>&1

case "$1" in
  start)
    echo "Starting heartbeat_daemon Daemon"
    # run application you want to start
    python3 /www/wpScripts/_connect/heartbeat.py &
    ;;
  stop)
    echo "Stopping heartbeat_daemon Daemon"
    # kill application you want to stop
    kill $(ps aux | grep "/www/wpScripts/_connect/heartbeat.py" | grep -v grep | awk '{print $2}') 
    ;;
  restart)
    echo "Restarting the heartbeat_daemon Daemon"
    kill $(ps aux | grep "python3 /www/wpScripts/_connect/heartbeat.py" | grep -v grep | awk '{print $2}') &
    /www/wpScripts/_connect/heartbeat.py &
    ;;
  *)
    echo "Usage: /etc/init.d/heartbeat_daemon  {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
