#! /bin/sh
# /etc/init.d/readLora_daemon

#
### BEGIN INIT INFO
#Provides:          readLora_daemon
#Processname:       readLora_daemon
#Required-Start:    $network
#Required-Stop:     $network
#Default-Start:     S 2 
#Default-Stop:      0 1 6
#Short-Description: ata Logger
#Description:       A Temperature data logger.
### END INIT INFO

#exec 1>/tmp/readLora_daemon.log 2>&1

case "$1" in
  start)
    echo "Starting readLora Daemon"
    # run application you want to start
    python3 /www/wpScripts/_dataloggers/readLora.py &
    ;;
  stop)
    echo "Stopping readLora Daemon"
    # kill application you want to stop
    kill $(ps aux | grep "/www/wpScripts/_dataloggers/readLora.py" | grep -v grep | awk '{print $2}') 
    ;;
  restart)
    echo "Restarting the readLora Daemon"
    kill $(ps aux | grep "python3 /www/wpScripts/_dataloggers/readLora.py" | grep -v grep | awk '{print $2}') &
    /www/wpScripts/_dataloggers/readLora.py &
    ;;
  *)
    echo "Usage: /etc/init.d/readLora_daemon  {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
