#! /bin/sh
# /etc/init.d/readDist_daemon

#
### BEGIN INIT INFO
#Provides:          readDist_daemon
#Processname:       readDist_daemon
#Required-Start:    $network
#Required-Stop:     $network
#Default-Start:     S 2 
#Default-Stop:      0 1 6
#Short-Description: Distance data Logger 
#Description:       Log the distance meter data.
### END INIT INFO

#exec 1>/tmp/readDist_daemon.log 2>&1

case "$1" in
  start)
    echo "Starting readDist Daemon"
    # run application you want to start
    python3 /www/wpScripts/_dataloggers/readDist.py &
    ;;
  stop)
    echo "Stopping readDist Daemon"
    # kill application you want to stop
    kill $(ps aux | grep "/www/wpScripts/_dataloggers/readDist.py" | grep -v grep | awk '{print $2}') 
    ;;
  restart)
    echo "Restarting the readDist Daemon"
    kill $(ps aux | grep "python3 /www/wpScripts/_dataloggers/readDist.py" | grep -v grep | awk '{print $2}') &
    /www/wpScripts/_dataloggers/readDist.py &
    ;;
  *)
    echo "Usage: /etc/init.d/readDist_daemon {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
